# Generated by Django 4.0.5 on 2022-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
